# Add application configuration variables here, as shown below.
#
# PUSHER_APP_ID: "2954"
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS
GMAIL_ID: sandeepkuvs
GMAIL_PASSWORD: Kssubrahmanyam
TMDB_API_KEY: c3871ea7f0402a006b8949e41643bd93
AWS_ACCESS_KEY_ID: AKIAJDFCUGIGBA63N4RQ
AWS_SECRET_ACCESS_KEY: 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
FOG_DIRECTORY: moviepulse
CARRIER_WAVE_SECRET_TOKEN: a0af1ed4ad46b5fafbafef7861d4ba3f8e5191ca57eb50fe82951c03a64cbaa3a2d3e3c2ddda88f62955a366a67d53664df8e1eb709752b1847b29fb8a869e1e
